<a href="https://colab.research.google.com/github/ptkoo/machineLearningJourney/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following tutorial is adapted from the Official PyTorch tutorials. https://pytorch.org/tutorials/

In [ ]:
import torch
import numpy as np

torch.__version__

'2.3.0+cu121'

# Tensors

Tensors are similar to NumPy's ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

Common operations for creation and manipulation of these Tensors are
similar to those for ndarrays in NumPy. (rand, ones, zeros, indexing,
slicing, reshape, transpose, cross product, matrix product, element wise
multiplication)

In [ ]:
# Example with 1-D data
data = [1.0, 2.0, 3.0]
x = torch.tensor(data)
print("Example with 1-D data")
print(x)

Example with 1-D data
tensor([1., 2., 3.])


In [ ]:
# Example with 2-D data
data = [[1., 2., 3.], [4., 5., 6]]
x = torch.tensor(data)
print("\nExample with 2-D data")
print(x)


Example with 2-D data
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# Example with 3-D data
data = [[[1.,2.], [3.,4.]],
        [[5.,6.], [7.,8.]]]
x = torch.Tensor(data)
print("\nExample with 3-D data")
print(x)


Example with 3-D data
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [ ]:
x.shape

torch.Size([2, 2, 2])

# Tensor Initialization

Empty tensors contain unknown values

In [ ]:
# Construct a 2x3 matrix, uninitialized
x = torch.empty(2, 3)
x

tensor([[-1.9085e+25,  3.1909e-41, -1.9611e+25],
        [ 3.1909e-41,  1.1210e-43,  0.0000e+00]])

Randomly initialize tensors

In [ ]:
# Construct a 2x3 matrix, randomly
x = torch.rand(2, 3)
x

tensor([[0.5534, 0.8988, 0.4501],
        [0.8176, 0.7103, 0.1208]])

Tensors with zeros or ones

In [ ]:
# Create a matrix of all zeros
x = torch.zeros(2, 3)
print("Matrix of zeros")
print(x.dtype)
print(x)

# Create a matrix of all zeros and explicitly set data type to be long int
x = torch.zeros(2, 3, dtype=torch.long)
print("\nMatrix of zeros typecasted to long")
print(x)

x = torch.ones(2, 3, dtype=torch.long)
print("\nMatrix of ones typecasted to long")
print(x)

Matrix of zeros
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Matrix of zeros typecasted to long
tensor([[0, 0, 0],
        [0, 0, 0]])

Matrix of ones typecasted to long
tensor([[1, 1, 1],
        [1, 1, 1]])


In [ ]:
x_ones = torch.ones_like(x)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 



# Tensor Size

In [ ]:
# Example with 1-D data
data = [1.0, 2.0, 3.0]
x = torch.tensor(data)
print("Example with 1-D data")
print(x)
print(x.size())
print(x.shape)

Example with 1-D data
tensor([1., 2., 3.])
torch.Size([3])
torch.Size([3])


In [ ]:
# Example with 2-D data
data = [[1., 2., 3.], [4., 5., 6]]
x = torch.tensor(data)
print("\nExample with 2-D data")
print(x)
print(x.size())
print(x.shape)


Example with 2-D data
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.Size([2, 3])


In [ ]:
# Example with 3-D data
data = [[[1.,2.], [3.,4.]],
        [[5.,6.], [7.,8.]]]
x = torch.tensor(data)
print("\nExample with 3-D data")
print(x)
print(x.size())
print(x.shape)


Example with 3-D data
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])


# Tensor Operations

In [ ]:
# Addition
x = torch.tensor([ 1., 2., 3. ])
y = torch.tensor([ 4., 5., 6. ])

# using arithmetic operation
z = x + y
print(z)

tensor([5., 7., 9.])


In [ ]:
# using method
print(torch.add(x, y))

tensor([5., 7., 9.])


In [ ]:
# using method and providing an output tensor as argument
output = torch.empty(3)
torch.add(x, y, out=output)
print(output)

tensor([5., 7., 9.])


In [ ]:
# In-place addition
x = torch.tensor([ 1., 2., 3. ])
y = torch.tensor([ 4., 5., 6. ])

y.add_(x)
print(y)

tensor([5., 7., 9.])


# Indexing

In [ ]:
x = torch.tensor([ 1., 2., 3. ])
x[0]

tensor(1.)

In [ ]:
x[0].item()

1.0

In [ ]:
x[1:]

tensor([2., 3.])

In [ ]:
data = [[1., 2., 3.], [4., 5., 6]]
x = torch.tensor(data)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x[1, 1]

tensor(5.)

In [ ]:
x[1, :]

tensor([4., 5., 6.])

In [ ]:
x[1, 1:]

tensor([5., 6.])

# Reshaping Tensors

In [ ]:
x = torch.arange(1, 7)
x

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
x.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
x.reshape(2, -1) # the size -1 is inferred from other dimensions

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.reshape(-1, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

# Converting to and from NumPy

In [ ]:
x = torch.arange(1, 7)
x_np = x.numpy()
x_np

array([1, 2, 3, 4, 5, 6])

In [ ]:
x_np = np.arange(1, 7)
x = torch.from_numpy(x_np)
x

tensor([1, 2, 3, 4, 5, 6])

# CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

If running on Colab, go to `Runtime` -> `Change runtime type` -> select GPU accelerator.

If running locally with CUDA GPUs, PyTorch should auto-detect the GPUs.

In [ ]:
print("CUDA available?", torch.cuda.is_available())

CUDA available? True


In [ ]:
x = torch.ones(1, 3)
x

tensor([[1., 1., 1.]])

In [ ]:
y = x.cuda()
y

tensor([[1., 1., 1.]], device='cuda:0')

In [ ]:
y.cpu()

tensor([1., 1., 1.])

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    x = torch.tensor([1.0, 2.0, 3.0])
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2., 3., 4.], device='cuda:0')
tensor([2., 3., 4.], dtype=torch.float64)


# Autograd: Automatic Differentiation

When training neural networks, the most frequently used algorithm is back propagation. In this algorithm, parameters (model weights) are adjusted according to the gradient of the loss function with respect to the given parameter.

torch.tensor is the central class of the package. If you set its attribute `.requires_grad` as `True`, it starts to track all operations on it. When you finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into `.grad` attribute.

To prevent tracking history (and using memory), you can also wrap the code block in with `torch.no_grad():`. This can be particularly helpful when evaluating a model because the model may have trainable parameters with `requires_grad=True`, but for which we don't need the gradients.

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)

# y was created as a result of an operation, so it has a grad_fn.

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
y.grad_fn

In [ ]:
z = y * y * 3
out = z.mean()

print("z:", z)
print("out:", out)

z: tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
out: tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
out.backward()

x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False
